#!/bin/bash

set -e

tag=v0.0.1
#$(./devstep -v)

owner='rvalyi'

echo "===> Building ${owner}/odoocker-devstep:${tag}"
docker build -t ${owner}/odoocker-devstep:${tag} .

echo "===> Building ${owner}/odoocker-devstep-pg:${tag}"
(cd embedded_posgtresql && docker build -t ${owner}/odoocker-devstep-pg:${tag} .)
